name: Python Package using Conda

on: [push]

jobs:
  build-tensorflow:
    runs-on: gcr.io/tensorflow/tensorflow
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v2
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
